novelpool/novelpool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('novelpoolapp.urls')),
]

novelpool/novelpoolapp/urls.py
from django.urls import path, include
from novelpoolapp.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('tutorial/', tutorial, name='tutorial'),
    path('novel/<int:novel_id>/read/<int:page_id>/', read, name='read'),
    #Novel
    path('novel/<int:novel_id>/', login_required(NovelView.as_view()), name='novel'),
    path('create/novel/', login_required(NovelCreateView.as_view()), name='create_novel'),
    path('edit/novel/<int:novel_id>/', login_required(NovelEditView.as_view()), name='edit_novel'),
    path('delete/novel/<int:novel_id>/', novel_delete, name='novel_delete'),
    #Chapter
    path('create/novel/<int:novel_id>/chapter/', login_required(ChapterCreateView.as_view()), name='create_chapter'),
    path('edit/novel/<int:novel_id>/chapter/<int:chapter_id>/', login_required(ChapterEditView.as_view()), name='edit_chapter'),
    path('novel/<int:novel_id>/chapter/<int:chapter_id>/', login_required(ChapterView.as_view()), name='chapter'),
    path('delete/chapter/<int:chapter_id>/', chapter_delete, name='delete_chapter'),
    #Page
    path('create/novel/<int:novel_id>/page/', login_required(PageCreateView.as_view()), name='create_page'),
    path('create/novel/<int:novel_id>/chapter/<int:chapter_id>/page/', login_required(PageCreateView.as_view()), name='create_page_with_chapter'),
    path('edit/novel/<int:novel_id>/page/<int:page_id>/', login_required(PageEditView.as_view()), name='edit_page'),
    path('novel/<int:novel_id>/page/<int:page_id>/', login_required(PageView.as_view()), name='page'),
    path('delete/page/<int:page_id>/', page_delete, name='delete_page'),
    #Selection
    path('create/novel/<int:novel_id>/page/<int:page_id>/selection/', login_required(SelectionCreateView.as_view()), name='create_selection'),
    path('edit/novel/<int:novel_id>/page/<int:page_id>/selection/<int:selection_id>/', login_required(SelectionEditView.as_view()), name='edit_selection'),
    path('novel/<int:novel_id>/page/<int:page_id>/selection/<int:selection_id>/', login_required(SelectionView.as_view()), name='selection'),
    path('delete/selection/<int:selection_id>/', selection_delete, name='delete_selection'),
    #Transition
    path('create/novel/<int:novel_id>/page/<int:page_id>/selection/<int:selection_id>/transition/', login_required(TransitionCreateView.as_view()), name='create_transition_with_selection'),
    path('create/novel/<int:novel_id>/page/<int:page_id>/transition/', login_required(TransitionCreateView.as_view()), name='create_transition'),
    path('edit/novel/<int:novel_id>/page/<int:page_id>/transition/<int:transition_id>/', transition_edit_or_create, name='edit_transition'),
    path('novel/<int:novel_id>/page/<int:page_id>/transition/<int:transition_id>/', login_required(TransitionView.as_view()), name='transition'),
    path('delete/transition/<int:transition_id>/', transition_delete, name='delete_transition'),
    #Profiles
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', login_required(ProfileView.as_view()), name='profile'),
    path('register/', register, name='register')
]

novelpool/novelpoolapp/models.py
from django.db import models
from enum import Enum
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.exceptions import PermissionDenied


class NovelStatus(Enum):
    DRAFT = 1
    WORK = 2


class Novel(models.Model):
    name = models.CharField('Название', max_length=200)
    description = models.TextField('Описание')
    status = models.IntegerField('Статус',default=1)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец')

    def __str__(self):
        return self.name
    
    def getFirstPage(self):
        first_page = self.page_set.filter(is_first=True).first()
        return first_page
    
    def hasFirstPage(self):
        return not self.getFirstPage() is None
    
    class Meta:
        verbose_name = 'Новелла'
        verbose_name_plural = 'Новеллы'

    def getOwner(self):
        return self.owner
    
    def validateUser(self, user):
        if self.getOwner() != user:
            raise PermissionDenied()
    
    def get_absolute_url(self):
        return reverse('novel', kwargs={'novel_id':self.id})


class Chapter(models.Model):
    name = models.CharField('Название', max_length=20)
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, verbose_name='Новелла')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Глава'
        verbose_name_plural = 'Главы'

    def getQuerySetByNovelId(novel_id):
        novel = Novel.objects.filter(id=novel_id).first()
        return Chapter.objects.filter(novel=novel).all()
    
    def getOwner(self):
        return self.novel.getOwner()
    
    def validateUser(self, user):
        if self.getOwner() != user:
            raise PermissionDenied()
    
    def get_absolute_url(self):
        return reverse('chapter', kwargs={'novel_id':self.novel.id, 'chapter_id':self.id})


class Page(models.Model):
    name = models.CharField('Название', max_length=20)
    text = models.TextField('Текст')
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, verbose_name='Глава')
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, verbose_name='Новелла')
    is_first = models.BooleanField('Является первой страницей', default=False)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = 'Страницы'

    def getOwner(self):
        return self.novel.getOwner()
    
    def validateUser(self, user):
        if self.getOwner() != user:
            raise PermissionDenied()
    
    def get_absolute_url(self):
        return reverse('page', kwargs={'novel_id':self.novel.id, 'page_id':self.id})


class Selection(models.Model):
    text = models.CharField('Ответ', max_length=500)
    page = models.ForeignKey(Page, on_delete=models.CASCADE, verbose_name='Страница')

    def __str__(self):
        return f'(Ответ) {self.page.name} - {self.text[:10]}'
    
    def hasNoTransition(self):
        transitions = self.transition_set.all()
        return transitions.count() == 0
    
    def getOwner(self):
        return self.page.getOwner()
    
    def validateUser(self, user):
        if self.getOwner() != user:
            raise PermissionDenied()
    
    def get_absolute_url(self):
        return reverse('selection', kwargs={'novel_id':self.page.novel.id, 'page_id':self.page.id, 'selection_id':self.id})
    
    class Meta:
        verbose_name = 'Вариант ответа'
        verbose_name_plural = 'Варианты ответов'


class Transition(models.Model):
    page_from = models.ForeignKey(Page, on_delete=models.CASCADE, related_name='outcoming_transitions', verbose_name='Страница отправления')
    page_to = models.ForeignKey(Page, on_delete=models.CASCADE, related_name='incoming_transitions', verbose_name='Страница назначения')
    selection = models.ForeignKey(Selection, on_delete=models.CASCADE, verbose_name='Выбор')
    description = models.CharField(max_length=1000, verbose_name='Описание')

    def __str__(self):
        return self.description
    
    class Meta:
        verbose_name = 'Переход'
        verbose_name_plural = 'Переходы'

    def getOwner(self):
        return self.page_from.getOwner()
    
    def validateUser(self, user):
        if self.getOwner() != user:
            raise PermissionDenied()
        
    def get_absolute_url(self):
        return reverse('transition', kwargs={'novel_id':self.page_from.novel.id, 'page_id':self.page_from.id, 'transition_id':self.id})

novelpool/novelpoolapp/forms.py
from .models import *
from django.forms import ModelForm, TextInput, Textarea, ModelChoiceField, BooleanField, Select, CharField, PasswordInput,ValidationError
#trying to push to dev branch

class UserRegistrationForm(ModelForm):
    password = CharField(label='Пароль', widget=PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Пароль'
            }))
    password2 = CharField(label='Повторите пароль', widget=PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Повторите пароль'
            }))


    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name',
            'email',
        ]
        widgets = {
            'username':TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Логин'
            }),
            'first_name':TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя'
            }),
            'last_name':TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия'
            }),
            'email':TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Адрес электронной почты'
            }),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError('Пароли не совпадают.')
        return cd['password2']


class NovelForm(ModelForm):
    class Meta:
        model = Novel
        fields = [
            'name',
            'description',
#            'owner'
        ]
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название'
            }),
            'description': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание'
            })

        }


class ChapterForm(ModelForm):
    class Meta:
        model = Chapter
        fields = [
            'name'
        ]
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название'
            })
        }
    

class PageForm(ModelForm):
    class Meta:
        model = Page
        chapter = ModelChoiceField(queryset=Chapter.objects.all(), to_field_name="name")
        is_first = BooleanField(label='Первая страница')
        fields = [
            'name',
            'text',
            'chapter',
            'is_first'
        ]
        widgets = {
            'name': TextInput(attrs = {
                'class': 'form-control',
                'placeholder': 'Введите название'
            }),
            'text': Textarea(attrs = {
                'class': 'form-control',
                'placeholder': 'Введите текст'
            })
        }

class SelectionForm(ModelForm):
    class Meta:
        model = Selection
        fields = [
            'text'
        ]
        widgets = {
            'text': TextInput(attrs = {
                'class': 'form-control',
                'placeholder': 'введите текст ответа'
            })
        }

class TransitionForm(ModelForm):
    class Meta:
        model = Transition
        fields = [
            'page_to',
            'selection',
            'description'
        ]
        widgets = {
            'page_to': Select(attrs = {
                'class': 'form-control'
            }),
            'selection': Select(attrs = {
                'class': 'form-control'
            }),
            'description': TextInput(attrs = {
                'class': 'form-control',
                'placeholder': 'Введите описание перехода'
            })
        }

novelpool/novelpoolapp/templates/novelpool/chapter.html
{% extends 'base.html' %}
{% block title %}
Глава {{ chapter.name }}
{% endblock %}

{% block content %}
<h1><a href = "{% url 'novel' novel_id=novel.id %}">{{ novel.name }}</a></h1>
<h2>Глава {{chapter.name}}</h2>

{% if user == chapter.getOwner %}
    <a href = "{% url 'edit_chapter' novel_id=novel.id chapter_id=chapter.id %}">Редактировать</a><br>
    <a href = "{% url 'create_page_with_chapter' novel_id=novel.id chapter_id=chapter.id %}">Добавить страницу</a><br>
    <a href = "{% url 'delete_chapter' chapter_id=chapter.id %}">Удалить</a>
{% endif %}
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/create_chapter.html
{% extends 'base.html' %}

{% block title %}
Создать главу к новелле {{novel.name}}
{% endblock %}

{% block content %}
{% if chapter %}
    <h1>Редактировать главу {{ chapter.name }} новеллы <a href="{% url 'novel' novel_id=novel.id%}">{{ novel.name }}</a></h1>
{% else %}
    <h1>Создать главу к новелле <a href="{% url 'novel' novel_id=novel.id%}">{{ novel.name }}</a></h1>
{% endif %}

{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {{ form.name }}
    <button type="submit" class="btn btn-success">Сохранить</button>
</form>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/create_novel.html
{% extends 'base.html' %}
{% block title %}
    Создать новеллу
{% endblock %}
{% block content %}
    {% if novel %}
        <h1>Редактировать новеллу</h1>
    {% else %}
        <h1>Создать новеллу</h1>
    {% endif %}
    {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.name }}<br>
        {{ form.description }}<br>
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/create_page.html
{% extends 'base.html' %}

{% block title %}
Создать страницу
{% endblock %}

{% block content %}
{% if page %}
    <h1>Редактировать страницу {{page.name}} новеллы <a href="{% url 'novel' novel_id=novel.id%}"></a></h1>
{% else %}
    <h1>Создать страницу для новеллы <a href="{% url 'novel' novel_id=novel.id%}"></a></h1>
{% endif %}
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
<form method="POST">
    {% csrf_token %}

    {{form.name}}<br>
    {{form.text}}<br>
    {{form.chapter}}<br>

    {{form.is_first}}<br>
    <button type="submit" class="btn btn-success">Сохранить</button>
</form>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/create_selection.html
{% extends 'base.html' %}

{% block title %}
{% if selection %}
    Редактировать выбор для страницы {{ page.name }}
{% else %}
    Создать выбор для страницы {{ page.name }}
{% endif %}
{% endblock %}

{% block content %}
{% if selection %}
    <h1>Редактировать выбор для страницы <a href="{% url 'page' novel_id=novel.id page_id=page.id %}">{{ page.name }}</a></h1>
{% else %}
    <h1>Создать выбор для страницы <a href="{% url 'page' novel_id=novel.id page_id=page.id %}">{{ page.name }}</a></h1>
{% endif %}
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}


<form method="POST">
    {% csrf_token %}

    {{ form.text }}<br>
    <button type="submit" class="btn btn-success">Сохранить</button>
</form>

{% endblock %}

novelpool/novelpoolapp/templates/novelpool/create_transition.html
{% extends 'base.html' %}

{% block title %}
    Создать переход со страницы {{ page.name }}
{% endblock %}

{% block content %}
    <h1>Создать переход со страницы {{ page.name }}</h1>

    {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
    {% endif %}
    {% if selection %}
        <div class="alert alert-primary">Выбор '{{ selection.text }}'</div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}

        {% if not selection %}
            <div class="form-group">
                <label for="{{ form.selection.id_for_label }}">{{ form.selection.label }}</label>
                {{ form.selection }}<br>
            </div>
            
        {% endif %}
        
        <div class="form-group">
            <label for="{{ form.page_to.id_for_label }}">{{ form.page_to.label }}</label>
            {{ form.page_to }}<br>
        </div>
        
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
            {{ form.description }}<br>
        </div>
        
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>

{% endblock %}

novelpool/novelpoolapp/templates/novelpool/index.html
{% extends 'base.html' %}

{% block title %}
NovelPool
{% endblock %}

{% block content %}
<h1>Доступные новеллы:</h1>
<ul>
{% for novel in novels %}
    <li><h2><a href = "{% url 'novel' novel_id=novel.id %}">{{ novel.name }}</a></h2></li>
    <p>{{ novel.description }}</p>
{% endfor %}
</ul>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/novel.html
{% extends 'base.html' %}

{% block title %}
{{novel.name}}
{% endblock %}
{% block content %}
<h1>{{novel.name}}</h1>
{{novel.description}}
<p><h3>Содержание:</h3></p>
<ul>
    {% for chapter in novel.chapter_set.all %}
    <li>
        <a href="{% url 'chapter' novel_id=novel.id chapter_id=chapter.id %}">{{ chapter.name }}</a>
        <ul>
            {% for page in chapter.page_set.all %}
                <li>
                    <a href="{% url 'page' novel_id=novel.id page_id=page.id %}">{{page.name}}</a>
                </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% if novel.getOwner == user %}
    <a href = "{% url 'edit_novel' novel_id=novel.id %}">Редактировать</a><br>
    <a href = "{% url 'create_chapter' novel_id=novel.id %}">Добавить главу</a><br>
    <a href = "{% url 'create_page' novel_id=novel.id %}">Добавить страницу</a><br>
    <a href = "{% url 'novel_delete' novel_id=novel.id %}" class = "delete_link">Удалить</a><br><!--TODO: сделать подтверждение удаления -->
{% endif %}

{% if novel.hasFirstPage %}
    <a href = "{% url 'read' novel_id=novel.id page_id=novel.getFirstPage.id %}">Читать!</a>
{% endif %}
{% endblock %}
$(document).on('click', '.delete_link', function(){
    return confirm('Вы уверены, что хотите удалить эту новеллу? {{ novel.name }}');
})

novelpool/novelpoolapp/templates/novelpool/page.html
{% extends 'base.html' %}

{% block title %}
Страница {{page.name}}
{% endblock %}

{% block content %}
<h1>{{page.name}}</h1>
<h3>{{page.chapter.name}}</h3>
<div align="center">{{page.text}}</div>
{% if page.is_first %}
    Первая страница <br>
{% endif %}
Доступные выборы:
<ul>
    {% for selection in page.selection_set.all %}
        <li><a href="{% url 'selection' novel_id=novel.id page_id=page.id selection_id=selection.id %}">{{ selection.text }}</a></li>
        <details>
            <summary>Переход</summary>
            {% for transition in selection.transition_set.all %}
                <p><a href="{% url 'transition' novel_id=novel.id page_id=page.id transition_id=transition.id %}">{{ transition.description }}</a></p>
            {% endfor %}
        </details>
    {% endfor %}
</ul>
{% if page.getOwner == user %}
    <a href="{% url 'edit_page' novel_id=novel.id page_id=page.id %}">Редактировать</a><br>
    <br>
    <a href="{% url 'create_selection' novel_id=novel.id page_id=page.id %}">Создать выбор</a><br>
    <a href="{% url 'create_transition' novel_id=novel.id page_id=page.id %}">Создать переход</a><br>
    <a href ="{% url 'delete_page' page_id=page.id %}">Удалить</a>
{% endif %}
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/profile.html
{% extends 'base.html' %}

{% block title %}
Профиль
{% endblock %}

{% block content %}
<h1>{{ user.first_name }} {{ user.last_name }}</h1>

<h1>Ваши новеллы:</h1>
<ul>
{% for novel in novels %}
    <li><h2><a href = "{% url 'novel' novel_id=novel.id %}">{{ novel.name }}</a></h2></li>
    <p>{{ novel.description }}</p>
{% endfor %}
</ul>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/read.html
{% extends 'base.html' %}

{% block title %}

{{ page.novel.name }}

{% endblock %}

{% block content %}
<h1>{{  page.novel.name }}</h1>
<div>{{ page.chapter.name }}</div>
<div>{{ page.text }}</div>

<ul>
    {% for select in selections %}
    <li><a href="{% url 'read' novel_id=page.novel.id page_id=select.transition_set.first.page_to.id %}">{{ select.text }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/selection.html
{% extends 'base.html' %}

{% block title %}
Выбор для страницы {{ page.name }}
{% endblock %}

{% block content %}
<h1>Выбор для страницы <a href="{% url 'page' novel_id=novel.id page_id=page.id %}">{{ page.name }}</a></h1>
<div align="center">{{ selection.text }}</div>
<a href="{% url 'edit_selection' novel_id=novel.id page_id=page.id selection_id=selection.id %}">Редактировать</a><br>
{% if selection.hasNoTransition %}
    <a href="{% url 'create_transition_with_selection' novel_id=novel.id page_id=page.id selection_id=selection.id %}">Создать переход по этому выбору</a><br>
{% endif %}
<a href ="{% url 'delete_selection' selection_id=selection.id %}">Удалить</a>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/transition.html
{% extends 'base.html' %}
{% block title %}
Переход {{ page_from.name }} - {{ page_to.name }}
{% endblock %}

{% block content %}
<h1>Переход <a href="{% url 'page' novel_id=novel.id page_id=page_from.id %}"> {{ page_from.name }} </a> - <a href="{% url 'page' novel_id=novel.id page_id=page_to.id %}"> {{ page_to.name }} </a></h1>
<h3>Выбор <a href="{% url 'selection' novel_id=novel.id page_id=page_from.id selection_id=selection.id %}"> {{selection.text}} </a></h3>
<div align="center">{{ transition.description }}</div>
<a href="{% url 'edit_transition' novel_id=novel.id page_id=page_from.id transition_id=transition.id %}">Редактировать</a><br>
<a href ="{% url 'delete_transition' transition_id=transition.id %}">Удалить</a>
{% endblock %}

novelpool/novelpoolapp/templates/novelpool/tutorial.html
{% extends 'base.html' %}
{% block title %}
Обучение
{% endblock %}
{% block content %}
<h1>Обучение</h1>
<p>Какое-то обучение</p>
{% endblock %}